=== thabz/Kalliope/data/kalliopework.dtd
<!ENTITY AElig "&#198;">
<!ENTITY Auml "&#196;">
<!ENTITY Epsilon "&#917;">
<!ENTITY Gamma "&#915;">
<!ENTITY Iota "&#921;">
<!ENTITY Kappa "&#922;">
<!ENTITY Lambda "&#923;">
<!ENTITY OElig "&#338;">
<!ENTITY Omega "&#937;">
<!ENTITY Omicron "&#927;">
<!ENTITY Pi "&#928;">
<!ENTITY Rho "&#929;">
<!ENTITY Sigma "&#931;">
<!ENTITY Upsilon "&#933;">
<!ENTITY Uuml "&#220;">
<!ENTITY acirc "&#226;">
<!ENTITY aelig "&#230;">
<!ENTITY agrave "&#224;">
<!ENTITY bdquo "&#8222;">
<!ENTITY dagger "&#8224;">
<!ENTITY deg "&#176;">
<!ENTITY eacute "&#233;">
<!ENTITY ecirc "&#234;">
<!ENTITY egrave "&#232;">
<!ENTITY infin "&#8734;">
<!ENTITY iuml "&#239;">
<!ENTITY ldquo "&#8220;">
<!ENTITY mdash "&#8212;">
<!ENTITY nbsp "&#160;">
<!ENTITY ocirc "&#244;">
<!ENTITY oelig "&#339;">
<!ENTITY ouml "&#246;">
<!ENTITY szlig "&#223;">
<!ENTITY thorn "&#254;">

<!ELEMENT kalliopework (workhead, workbody?)>
<!ATTLIST kalliopework
  id CDATA #REQUIRED
  author CDATA #REQUIRED
  status CDATA #IMPLIED
  type CDATA #IMPLIED
  parent CDATA #IMPLIED>

<!ELEMENT workhead ANY>
<!ELEMENT workbody ANY>
<!ELEMENT text ANY>
<!ATTLIST text
  id CDATA #IMPLIED
  variant CDATA #IMPLIED
  aliases CDATA #IMPLIED
  skip-index CDATA #IMPLIED
  lang CDATA #IMPLIED
  ignore-tests CDATA #IMPLIED>
<!ELEMENT poem ANY>
<!ATTLIST poem id CDATA #IMPLIED>
<!ELEMENT prose ANY>
<!ATTLIST prose font-size CDATA #IMPLIED>
<!ELEMENT prosa ANY>
<!ELEMENT section ANY>
<!ATTLIST section
  id CDATA #IMPLIED
  level CDATA #IMPLIED
  variant CDATA #IMPLIED
  aliases CDATA #IMPLIED>
<!ELEMENT subwork ANY>
<!ATTLIST subwork ref CDATA #REQUIRED>
<!ELEMENT content ANY>

<!ELEMENT head ANY>
<!ELEMENT body ANY>
<!ATTLIST body xml:space (default|preserve) "preserve">
<!ELEMENT title ANY>
<!ATTLIST title force-index CDATA #IMPLIED>
<!ELEMENT year ANY>
<!ELEMENT subtitle ANY>
<!ELEMENT suptitle ANY>
<!ELEMENT firstline ANY>
<!ATTLIST firstline force-index CDATA #IMPLIED>
<!ELEMENT indextitle ANY>
<!ELEMENT toctitle ANY>
<!ELEMENT linktitle ANY>
<!ELEMENT breadcrumbtitle ANY>
<!ELEMENT nofirstline ANY>
<!ELEMENT keywords ANY>
<!ELEMENT source ANY>
<!ATTLIST source
  id CDATA #IMPLIED
  in CDATA #IMPLIED
  pages CDATA #IMPLIED
  facsimile CDATA #IMPLIED
  facsimile-pages CDATA #IMPLIED
  facsimile-pages-num CDATA #IMPLIED
  facsimile-pages-offset CDATA #IMPLIED>
<!ELEMENT dates ANY>
<!ELEMENT published ANY>
<!ELEMENT written ANY>
<!ELEMENT performed ANY>
<!ELEMENT event ANY>
<!ELEMENT begivenhed ANY>

<!ELEMENT notes ANY>
<!ELEMENT note ANY>
<!ATTLIST note
  xml:space (default|preserve) "preserve"
  type CDATA #IMPLIED
  lang CDATA #IMPLIED
  unknown-original-by CDATA #IMPLIED>
<!ELEMENT quality ANY>
<!ELEMENT pictures ANY>
<!ELEMENT picture ANY>
<!ATTLIST picture
  src CDATA #IMPLIED
  type CDATA #IMPLIED
  year CDATA #IMPLIED
  artwork CDATA #IMPLIED
  museum CDATA #IMPLIED
  invnr CDATA #IMPLIED
  objid CDATA #IMPLIED
  wikidata CDATA #IMPLIED>

<!ELEMENT poetry ANY>
<!ATTLIST poetry font-size CDATA #IMPLIED>
<!ELEMENT quote ANY>
<!ATTLIST quote
  font-size CDATA #IMPLIED
  margin-left CDATA #IMPLIED>
<!ELEMENT a ANY>
<!ATTLIST a
  href CDATA #IMPLIED
  poet CDATA #IMPLIED
  poem CDATA #IMPLIED
  work CDATA #IMPLIED
  keyword CDATA #IMPLIED
  person CDATA #IMPLIED
  bible CDATA #IMPLIED
  type CDATA #IMPLIED>
<!ELEMENT xref ANY>
<!ATTLIST xref
  poem CDATA #IMPLIED
  bibel CDATA #IMPLIED
  type CDATA #IMPLIED>
<!ELEMENT b ANY>
<!ELEMENT i ANY>
<!ELEMENT sc ANY>
<!ELEMENT small ANY>
<!ELEMENT sup ANY>
<!ELEMENT s ANY>
<!ELEMENT u ANY>
<!ELEMENT num ANY>
<!ELEMENT nonum ANY>
<!ELEMENT resetnum ANY>
<!ELEMENT center ANY>
<!ELEMENT right ANY>
<!ELEMENT margin ANY>
<!ELEMENT metrik ANY>
<!ELEMENT wrap ANY>
<!ELEMENT line ANY>
<!ELEMENT br ANY>
<!ELEMENT hr ANY>
<!ATTLIST hr width CDATA #IMPLIED>
<!ELEMENT pb ANY>
<!ATTLIST pb n CDATA #IMPLIED>
<!ELEMENT img ANY>
<!ATTLIST img
  src CDATA #IMPLIED
  alt CDATA #IMPLIED
  width CDATA #IMPLIED>
<!ELEMENT colored ANY>
<!ATTLIST colored color CDATA #IMPLIED>
<!ELEMENT footnote ANY>
<!ELEMENT biblio ANY>
<!ELEMENT asterism ANY>
<!ELEMENT block-center ANY>
<!ELEMENT two-columns ANY>
<!ELEMENT column ANY>
<!ELEMENT w ANY>

=== thabz/Kalliope/fdirs/winter/1872.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kalliopework SYSTEM "../../data/kalliopework.dtd">
<kalliopework id="1872" author="winter" status="complete" type="poetry">
<workhead>
    <title>En Samling Vers</title>
    <year>1872</year>
    <notes>
        <note>Teksten følger Christian Winther: <i>En Samling Vers</i>, C.A. Reitzels Forlag, Kbh., 1872.</note>
        <note>Noter med en foranstillet asterisk er digterens egne.</note>
        <note>Winthers <a work="winter/1860"><i>Samlede Digtninger</i></a>, bd. 1-9, Winther og Liebenberg (red.), C.A. Reitzels Forlag, Kbh., udkom 1860. <a work="winter/1865"><i>Brogede Blade</i> (1865)</a> fungerede som bind 10, og nærværende <i>En Samling Vers</i> (1872) fungerede som bind 11.</note>
    </notes>
    <pictures>
        <picture src="1872-p1.jpg">Titelbladet til <i>En Samling Vers</i> (1872) lyder ,,En Samling Vers / af / Christian Winther. // Kjøbenhavn. / C. A. Reitzels Forlag. / 1872.''</picture>
    </pictures>
    <source facsimile="4135818351_color" facsimile-pages-num="624" facsimile-pages-offset="374">Christian Winther: <i>En Samling Vers</i>, C.A. Reitzels Forlag, Kbh., 1872.</source>
</workhead>
<workbody>

<section id="winther2018090102" variant="winther2018083103">
<head>
    <title>Til Een</title>
    <notes>
        <note>Addendum til »Til Een« fra <i>Digtninger</i> (1843).</note> 
    </notes>
    <source pages="1-77"/>
</head>
<content>

<poem id="winter2018082601">
<head>
    <title>Tilegnelse</title>
    <firstline>Der flyver mangen Fugl omkring</firstline>
    <source pages="3-4"/>
    <quality>korrektur1,kilde,side</quality>
</head>
<body>
Der flyver mangen Fugl omkring,
Der ganger Dyr i Dale,
Som nok gad sagt os mange Ting,
Hvis blot de kunde tale.
Hvi skulde jeg, som har en Mund,
Da ei min Mund oplukke
For Dig og fra mit Hjertes Grund
Udsende Sorg og Sukke?

Saa vil jeg vove end een Gang
At see mig om paa Veien
Og stemme op en gammel Sang,
Som fordum var min egen;
Ret som den lille Fugl heel rap,
Dulgt under Vaarens Blade,
Begynder, hvor i Høst den slap,
Med sine Triller glade.

Min Sang, om er <w>din</w> Eiendom,
So naaer til Fleres Øre,
Som fagtens ville enes om
Den frem til Doms at føre.
Ren kan jeg om <w>din</w> læbe see
Et Smiil og fra <w>dit</w> Øie,
Saa maae <w>de</w> græde eller lee, -
Det agter jeg kun føie.
</body>
</poem>

<poem id="winter2018082602">
<head>
    <title><num>1.</num>Besøg paa Parnas</title>
    <toctitle><num>1.</num>Besøg paa Parnas</toctitle>
    <indextitle>Besøg paa Parnas</indextitle>
    <linktitle>Besøg paa Parnas</linktitle>
    <subtitle>Den 7de December 1858.</subtitle>
    <firstline>Forleden gik jeg op til Parnas</firstline>
    <source pages="5-25"/>
    <keywords>petrarca</keywords>
    <quality>korrektur1,kilde,side</quality>
</head>
<body>
Forleden gik jeg op til Parnas.
Jeg havde i Lommen Attest og Pas
Fra Etatsraaden og andre Critikere,
Fra Tydske, som endnu var vittigere;
Saa uden Vrøvl Mercurius
Mig aabned det fornemme Huus,
Tog mine Galocher, Stok og Frak
Og peged paa det næste Gemak,
Idet han sagde med venlig Stemme:
,,Han Selv og Frøknerne er hjemme;
Nu nys de Kaffe drukket har
Og gjerne mod Visiter ta'er.''
Jeg traadte ind og fandt dem Alle
Forsamlede i den store Halle.
Jeg nærmed mig den klare Sol,
Phøbus Apollo paa hans Stol;
Med Morgenskoe, heel skjønt brodered',
I Fløiels Slobrok og fint friseret,
Han sad og hamred paa Claveret
Med Pen i Mund og componered.
Saa nynned han lidt, og saa han skrev;
Et Partitur det sagtens blev, -
Jeg tænker, vist de dyre Blade
Skal sendes Hartmann eller Gade.
Da han mig saae, han smed sin Pen
Og raabte: ,,Er Du der igjen!
Jeg kan mig tænke, hvad Du vil,
Men jeg veed intet Raad dertil.
Du kan ei <w>Hesten</w> mere faae,
Den kan ei flyve, næppe gaae,
Den er udaset, og den maa
Paa Skolen ud og see at naae
Igjen til sine tabte Kræfter,
Hvis den skal tjene meer herefter.
De komme her og overhænge
Mig for det stakkels Dyr saalænge,
Til det af Skridtgang, Trav, Galop
Tilsidst mig slides ganske op.
De rende her i mine Sale,
Qvinder og Mænd, som de var gale,
Og paastaae, at for deres Natur
Det passer at faae en Ridetour.
En heel Armee har villet ride;
Det ville I ogsaa faae at vide
Histnede, thi hvo een Gang reed
Den Hest, ei tie kan dermed.
Og nu det stakkels Kræ jo maa
Tillige med Damesadel gaae.
Saameget Slid den ikke taaler.
Jeg sværger det ved mine Straaler,
Den skal nu hvile sig! - Og saa
Er Du ei ræd jo for at gaae
Paa dine Been? Jeg veed, for Pokker!
Du pleier helst at gaae paa Sokker.
Saa sok Du hen til disse Piger;
Naar dem et venligt Ord Du siger,
Saa hjælpe de Dig nok paa Vei, -
Saa slemme er de rigtig ei!
Idag jeg selv er ophængt, Du!
Jeg kan Dig ikke hjælpe nu.
Det er mig ikke lidt til Plage
Hver Dag i Solens Vogn at age
Om Sommeren - jeg maa bekjende -
Fra Morgen og til Aftens Ende;
Som <w>nu</w> den Tour er snart forbi,
Saa har jeg Tid til Poesie,
Musik og andre slige Sager,
Hvorom de mig dernede plager.''

    Saa dasked han mig paa min Skulder
Og rulled med gevaltigt Bulder
Sin Haand hen over Claviaturet
Og skrev igjen paa Partituret.

    Jeg saae mig om og tøved lidt.
Enhver i Salen havde Sit
At tage Vare. Længst derinde
Jeg saae min yndige Veninde,
Erato, ligge i Sophakrog
Og ivrigt læse i en Bog,
Mens af og til et Smiil hun drog.
Jeg kunde ei see Bogens Titel, -
Maaskee Petrarca eller Tom Little.
Hun nikked, som til en gammel Ven,
Og gav sig til sin Bog igjen.

    Urania, med Briller paa,
Med pjusket Haar og Strømper blaae,
Ved Vindvet læste om Kometen.
Hun spurgte mig: ,,Hør, har Du seet'en?''
Jeg svared ,,Ja!'' og skyndte mig
Afsted; thi jeg har Skræk for slig
Høilærd Mandinde, - jeg gyser ret
Ved Tanken blot; hun saare let
Mig sætter i Astronomien,
Jeg er kun slet bevandret i'en;
Vistnok et <i>Non</i> hun gav mig for den.
Ak nei! jeg holder mig til Jorden.

    Forbi Kalliope paa Taa
Jeg heel ærbødig monne gaae.
Homer ved hendes Fødder laae,
Mens hun i Nordens Saga-Taage
Det havde fundet svært at vaage,
Saa med en Skindbog paa sit Skjød
En liflig Middagsluur hun nød.

    Terpsichore - hen ved en Side -
Let paa Parquettet saae jeg glide.
Hun øved sig nok i nogle Trin,
Som rigtig kunde gjøre Vind,
Ret sirlige, men meer forfløine,
End det var godt for unge Øine.
For mig hun ikke sig geneerte,
Men snoede sig og pirouetteerte, -
Det gik som Stikker paa en Tromme.
Hun raabte, da hun saae mig komme:
,,Siig mig dog, Du! hvad maa jeg høre,
Hvordan det er, I jer opføre?
I rende jo der og sværme og sukke
For den uægte spanske Dukke!
Dog ligegodt, <w>hvor</w> hun er fra, -
Hun kan dog ikke disse <i>Pas</i>.''
Og dermed slog hun op med Benet,
Saa jeg blev staaende forstenet,
Til hun med Fingerkys og Blik
Mig vinked bort; - jeg videre gik.

    Hist Klio sad med Haand paa Kind,
Af Læsning næsten døv og blind.
Der taarned sig paa hendes Bord
En Bunke Bøger, høi og stor,
Og rundt omkring paa Gulvet laae
Aviser og Blade, store og smaa.
<w>Nu</w> var hun netop meget lidende, -
Hun læste Danmarks Rigsdagstidende.

    Lidt hen foran en Vindvespille,
Høit kneisende og stolt og stille,
Melpomene stod for et Speil,
Og, hvis jeg ikke tager feil,
Hun sig i Attituder øved, -
Nu dette Blik, nu hiint hun prøved;
Hun slængte Shawlet over Armen,
Hun trykked Haanden imod Barmen,
Hun bistert ind i Speilet stirred,
Frem tog hun saa et Skridt, - da dirred
Ret artigt hendes Crinoline,
Og brat hun tog en anden Mine.
Jeg nærer dyb Respect for hende;
Men angst jeg er, maa jeg bekjende,
For hendes Jammer uden Ende,
For det, der traver høit og rører,
Som altid hun i Munden fører.
Ved dette Seige, dette Brede,
Oprigtigt talt, jeg føler Lede,
<w>Jeg kjeder mig,</w> - og derfor her
Jeg hende ikke kom for nær,
Men tog en Omvei for at naae
Hen til den blomstersmykte Vraa,
Hvor Polyhymnia jeg saae.
Der sad hun paa en Art af Throne,
Om Haaret laae en Rosenkrone,
Hun støtted let sin fyldige Arm
Paa Davidsharpens gyldne Karm.
Jeg knæled ned. Hun løfted frem
Den ene Fod med Kjolens Bræm,
Som jeg til Læben ydmygt fik
Og kyssed - efter gammel Skik.

    Ei, ei! so sieht man Ihn doch wieder!
Saa talte hun; ,,was will Er? Lieder?
Steh' Er nur auf, sag' an, mein Guter!
Wie geht es Ihm? und sonst, was thut Er?
Er stutzt, weil ich Ihn deutsch anrede?
Die Sprache? - ach, ich brauche jede!
Drann soll Er keinen Anstoß nehmen.
Aus Leipzig, Hamburg, Stuttgart, Bremen
Viele Dichter, Kind und Weib und Mann,
Mich gingen jüngst um Hülfe an.
Sie haben lange hier gezandert,
Und vielfach wurde denn geplaudert;
Hab' auch den Schiller jüngst gelesen,
Daher kömmt mir das deutsche Wesen.
Doch laß' Er deshalb sich nicht stören,
Ich mag wohl auch mal Dänisch hören.
Er will ein Lied zum neuen Jahr
Für die Frau Liebste? - das ist klar.
Er soll es haben,'' sagde hun
Og rørte sagte ved min Mund
Med gyldne Plecter, og nu foer
Mig let fra Læben Festens Ord.

    <w>Du</w> er en Danneqvinde god,
Med freidigt Sind og dristigt Mod;
Du nærer i en trofast Barm
En Tanke klar, en Lue varm.
Jeg derfor knytted i min Sang
For Dig, min Ven, og Danevang
Tilsammen Ønsker og det Haab,
At snart af Sorgens bittre Daab
I Begge maatte løftes ud
Ved Naadens og ved Kraftens Gud!
- Hvad jeg for Tydsken ønsked tillige,
Behøver jeg vel knap at sige.

    Hun hørte ikke gjerne Sligt;
Og da jeg havde sagt mit Digt
Og vilde knæle - efter Pligt,
Saa vinked hun mig bort, lidt mut,
Og mumlede: ,,Schon gut, schon gut!''

    Før jeg mig nærmed til den Næste,
Jeg maatte uvilkaarligt fæste
Mit Øie paa en rank Figur,
Der læned sig mod Salens Muur.
Det var Thalia, den milde, glade!
Men hvor var Kindens Rosenblade?
Hvor var de skjelmske Glimt i Øiet,
Som gjorde mig saa tidt fornøiet? -
Jeg nærmede mig heel beskeden
Og spurgte: ,,Hvad har jaget Freden
Fra dette Hjerte? Hvo har vovet
I Sorg at bøie dette Hoved?
At blege disse Rosers Lød?
At sløve disse Stjerners Glød?''

    Her saae hun op og mig afbrød:.
Du spørger? ak, hvor kan Du spørge?
Har jeg da Grund ei til at sørge?
I eders pralende Kjøbenhavn,
Hvor haanes ikke der mit Navn!
